### ISSUE TITLE
Gem version >=1.20.0 requires Ruby >=1.9

### ISSUE THREAD

**Issue by paulosilva86** [stretcher/stretcher#86]
We're using Stretcher on a legacy project that uses Ruby 1.8.7 and Rails 2.3.18.
When we tried upgrading to the latest version (1.21.1), we caught an exception on our tests. Digging deeper we found out that the new alias.rb class that was introduced in version 1.20.0 (#57) uses Ruby's new hash syntax. So, since version 1.20.0 you have to use Ruby >=1.9.

It would be nice if the hash syntax used throughout the gem was consistent. In this case, using the hash rocket syntax so older versions of Ruby are still supported.

**Comment by andrewvc** [comment]
Hmmm, thanks for the feedback, but we decided that we wouldn't support ruby <= 1.9 given the extreme age of 1.8.7. I apologize for the inconvenience.
